print("Tolin Elvin")
print("Maniwaya Sta. Cruz Marinduque")
print("October 20 2002")
print("")
print("Marinduque State College")
print("BSIT")
print("2nd year")
print("")
print("swimming")
print("watching anime")
print("drawing")
print("singing")
print("reading mangga")